spring:
  datasource:
    url: jdbc:mysql://1.15.129.32:3306/test1?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: test1
    password: 1750340569!Xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template-location: true
  redis:
    host: 1.15.129.32
    port: 6379
    database: 0
    password: 123456
mybatis:
  type-aliases-package: com.example.scoringsystem.bean
  mapper-locations: classpath:mybatis/mapper/*.xml
logging:
  level:
    root: debug
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


server:
  #端口号
  port: 8888
  #项目名，如果不设定，默认是 /