spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=Asia/Shanghai&useUnicode=true&zeroDateTimeBehavior=convertToNull&autoReconnect=true&characterEncoding=utf-8
    username: root
    password: 1750340569!Xm
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template-location: true
mybatis:
  type-aliases-package: com.example.scoring_system.bean
  mapper-locations: classpath:mybatis/mapper/*.xml

